---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt: pkg={{ item }}
    state: present
    with_items:
      - curl
      - wget
      - htop
    update_cache: true
    when: ansible_os_family == 'Debian'

    - name: Install packages
    yum: pkg={{ item }}
    state: present
    with_items:
      - curl
      - wget
      - htop
    update_cache: true
    when: ansible_os_family == 'RedHat'
